### ISSUE TITLE
Cant actually Craft.

### ISSUE THREAD

**Issue by DougJudy69** [RexShack/rsg_weaponcrafting#1]
Copying works but u cant craft things like I had all the materials for weapon parts and when I open the menu and click on weapon parts nothing happens

**Comment by RexShack** [comment]
have you got all the required resources installed and started

qb-core : https://github.com/qbcore-framework/qb-core
qb-target : https://github.com/qbcore-framework/qb-target
qb-menu : https://github.com/qbcore-framework/qb-menu
qb-input : https://github.com/qbcore-framework/qb-input
bob74_ipl : https://github.com/qbcore-framework/bob74_ipl

**Comment by DougJudy69** [comment]
yep

**Comment by RexShack** [comment]
tested on my server and works ok so not sure what is happening with yours

**Comment by RexShack** [comment]
just done a major update.. try downloading it again and ensure that your clear your game and server cache

**Comment by RexShack** [comment]
no response closed
